### ISSUE TITLE
有办法在maskView上添加视图吗

### ISSUE THREAD

**Issue by FoneG** [zhusongyu/ZSYMaskView#1]

**Comment by zhusongyu** [comment]
maskView起的是遮罩效果，需要在上面加视图吗？可以提供具体案例参考一下吗？

**Comment by FoneG** [comment]
譬如这种场景：手指部分会在maskView的区域 ![截屏2021-11-30 下午7 52 37](https://user-images.githubusercontent.com/15395364/144042688-9f31b734-ea99-40ca-8067-94a37bcd8760.png)

**Comment by zhusongyu** [comment]
> 譬如这种场景：手指部分会在maskView的区域 ![截屏2021-11-30 下午7 52 37](https://user-images.githubusercontent.com/15395364/144042688-9f31b734-ea99-40ca-8067-94a37bcd8760.png)

了解了，但是我的实现是基于frame裁切的，才有的镂空效果，这个可能需要换一个方案了，如果是静态页面的话，直接画一个页面也比较方便。

**Comment by FoneG** [comment]
。。。   突然发现你这个必须点亮整个矩形区域啊，就算有圆角的也不行    好鸡肋
